// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portfolio.Infrastructure.Data;

#nullable disable

namespace Portfolio.Infrastructure.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20260305151547_InitialDataJson")]
    partial class InitialDataJson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Portfolio.Domain.Entities.BlockType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsMultiple")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("BlockType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "INTRO",
                            IsMultiple = false
                        },
                        new
                        {
                            Id = 2,
                            Code = "SKILL",
                            IsMultiple = true
                        },
                        new
                        {
                            Id = 3,
                            Code = "EDUCATION",
                            IsMultiple = true
                        },
                        new
                        {
                            Id = 4,
                            Code = "DIPLOMA",
                            IsMultiple = true
                        },
                        new
                        {
                            Id = 5,
                            Code = "EXPERIMENT",
                            IsMultiple = true
                        },
                        new
                        {
                            Id = 6,
                            Code = "PROJECT",
                            IsMultiple = true
                        },
                        new
                        {
                            Id = 7,
                            Code = "AWARD",
                            IsMultiple = true
                        },
                        new
                        {
                            Id = 8,
                            Code = "ACTIVITIES",
                            IsMultiple = true
                        },
                        new
                        {
                            Id = 9,
                            Code = "OTHERINFO",
                            IsMultiple = true
                        },
                        new
                        {
                            Id = 10,
                            Code = "REFERENCE",
                            IsMultiple = true
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("IX_Portfolio_EmployeeId");

                    b.ToTable("Portfolio", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.PortfolioBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlockTypeId")
                        .HasColumnType("int");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("{}");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BlockTypeId");

                    b.HasIndex("PortfolioId", "BlockTypeId", "DisplayOrder")
                        .HasDatabaseName("IX_Block_Portfolio_Type_Order");

                    b.ToTable("PortfolioBlock", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.PortfolioBlock", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.BlockType", "BlockType")
                        .WithMany("PortfolioBlocks")
                        .HasForeignKey("BlockTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Portfolio.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany("Blocks")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockType");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.BlockType", b =>
                {
                    b.Navigation("PortfolioBlocks");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Portfolio", b =>
                {
                    b.Navigation("Blocks");
                });
#pragma warning restore 612, 618
        }
    }
}
