// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portfolio.Infrastructure.Data;

#nullable disable

namespace Portfolio.Infrastructure.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    partial class PortfolioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Portfolio.Domain.Entities.BlockType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsMultiple")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("BlockType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "INTRO",
                            IsActive = true,
                            IsMultiple = false
                        },
                        new
                        {
                            Id = 2,
                            Code = "SKILL",
                            IsActive = true,
                            IsMultiple = true
                        },
                        new
                        {
                            Id = 3,
                            Code = "EDUCATION",
                            IsActive = true,
                            IsMultiple = true
                        },
                        new
                        {
                            Id = 4,
                            Code = "DIPLOMA",
                            IsActive = true,
                            IsMultiple = true
                        },
                        new
                        {
                            Id = 5,
                            Code = "EXPERIMENT",
                            IsActive = true,
                            IsMultiple = true
                        },
                        new
                        {
                            Id = 6,
                            Code = "PROJECT",
                            IsActive = true,
                            IsMultiple = true
                        },
                        new
                        {
                            Id = 7,
                            Code = "AWARD",
                            IsActive = true,
                            IsMultiple = true
                        },
                        new
                        {
                            Id = 8,
                            Code = "ACTIVITIES",
                            IsActive = true,
                            IsMultiple = true
                        },
                        new
                        {
                            Id = 9,
                            Code = "OTHERINFO",
                            IsActive = true,
                            IsMultiple = true
                        },
                        new
                        {
                            Id = 10,
                            Code = "REFERENCE",
                            IsActive = true,
                            IsMultiple = true
                        });
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Compliment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PortfolioId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_Compliment_Portfolio_User_Active")
                        .HasFilter("[State] <> 3");

                    b.HasIndex("PortfolioId", "UserId", "State")
                        .HasDatabaseName("IX_Compliment_Portfolio_User_State");

                    b.ToTable("Compliment", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprovedComplimentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<decimal?>("AverageScore")
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("ComplimentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Embedding")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmbeddingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("EmbeddingUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmbeddingVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsMain")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModeratedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModerationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ModerationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("PendingReview");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("IX_Portfolio_EmployeeId");

                    b.HasIndex("EmployeeId", "IsMain")
                        .IsUnique()
                        .HasDatabaseName("UX_Portfolio_EmployeeId_IsMain")
                        .HasFilter("[IsMain] = 1");

                    b.ToTable("Portfolio", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.PortfolioBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlockTypeId")
                        .HasColumnType("int");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("{}");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<string>("Variant")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("BlockTypeId");

                    b.HasIndex("PortfolioId", "BlockTypeId", "DisplayOrder")
                        .HasDatabaseName("IX_Block_Portfolio_Type_Order");

                    b.ToTable("PortfolioBlock", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.PortfolioFollow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FollowedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("DATEADD(HOUR, 7, GETUTCDATE())");

                    b.Property<string>("InterestLevel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("PortfolioId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("IX_PortfolioFollow_CategoryId");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("IX_PortfolioFollow_CompanyId");

                    b.HasIndex("PortfolioId")
                        .HasDatabaseName("IX_PortfolioFollow_PortfolioId");

                    b.HasIndex("CompanyId", "PortfolioId")
                        .IsUnique()
                        .HasDatabaseName("UX_PortfolioFollow_Company_Portfolio");

                    b.ToTable("PortfolioFollow", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.PortfolioFollowCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("DATEADD(HOUR, 7, GETUTCDATE())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("IX_PortfolioFollowCategory_CompanyId");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_PortfolioFollowCategory_Company_Code");

                    b.ToTable("PortfolioFollowCategory", (string)null);
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Compliment", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany("Compliments")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.PortfolioBlock", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.BlockType", "BlockType")
                        .WithMany("PortfolioBlocks")
                        .HasForeignKey("BlockTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Portfolio.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany("Blocks")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockType");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.PortfolioFollow", b =>
                {
                    b.HasOne("Portfolio.Domain.Entities.PortfolioFollowCategory", "Category")
                        .WithMany("Follows")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Portfolio.Domain.Entities.Portfolio", "Portfolio")
                        .WithMany("Follows")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.BlockType", b =>
                {
                    b.Navigation("PortfolioBlocks");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.Portfolio", b =>
                {
                    b.Navigation("Blocks");

                    b.Navigation("Compliments");

                    b.Navigation("Follows");
                });

            modelBuilder.Entity("Portfolio.Domain.Entities.PortfolioFollowCategory", b =>
                {
                    b.Navigation("Follows");
                });
#pragma warning restore 612, 618
        }
    }
}
