// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Subscription.Infrastructure.Data;

#nullable disable

namespace Subscription.Infrastructure.Migrations
{
    [DbContext(typeof(SubscriptionDbContext))]
    partial class SubscriptionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Subscription.Domain.Entities.OutboxEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Status");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("OutboxEvents", (string)null);
                });

            modelBuilder.Entity("Subscription.Domain.Entities.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillingCycle")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Plans", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BillingCycle = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Basic free plan",
                            IsActive = true,
                            Name = "Free",
                            Price = 0m
                        },
                        new
                        {
                            Id = 2,
                            BillingCycle = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Professional plan with advanced features",
                            IsActive = true,
                            Name = "Pro",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 3,
                            BillingCycle = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Premium plan with unlimited access",
                            IsActive = true,
                            Name = "Premium",
                            Price = 19.99m
                        });
                });

            modelBuilder.Entity("Subscription.Domain.Entities.PlanFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FeatureKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FeatureName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PlanId", "FeatureKey")
                        .IsUnique();

                    b.ToTable("PlanFeatures", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FeatureKey = "MAX_APPLY",
                            FeatureName = "Max Applications",
                            IsActive = true,
                            PlanId = 1,
                            Type = 2,
                            Value = "5"
                        },
                        new
                        {
                            Id = 2,
                            FeatureKey = "MAX_PORTFOLIOS",
                            FeatureName = "Max Portfolios",
                            IsActive = true,
                            PlanId = 1,
                            Type = 2,
                            Value = "1"
                        },
                        new
                        {
                            Id = 3,
                            FeatureKey = "AI_MATCHING",
                            FeatureName = "AI Matching",
                            IsActive = true,
                            PlanId = 1,
                            Type = 1,
                            Value = "false"
                        },
                        new
                        {
                            Id = 4,
                            FeatureKey = "BOOST_PROFILE",
                            FeatureName = "Profile Boost",
                            IsActive = true,
                            PlanId = 1,
                            Type = 1,
                            Value = "false"
                        },
                        new
                        {
                            Id = 5,
                            FeatureKey = "COMPLIMENT_ACCESS",
                            FeatureName = "Compliment Access",
                            IsActive = true,
                            PlanId = 1,
                            Type = 1,
                            Value = "false"
                        },
                        new
                        {
                            Id = 6,
                            FeatureKey = "MAX_APPLY",
                            FeatureName = "Max Applications",
                            IsActive = true,
                            PlanId = 2,
                            Type = 2,
                            Value = "20"
                        },
                        new
                        {
                            Id = 7,
                            FeatureKey = "MAX_PORTFOLIOS",
                            FeatureName = "Max Portfolios",
                            IsActive = true,
                            PlanId = 2,
                            Type = 2,
                            Value = "5"
                        },
                        new
                        {
                            Id = 8,
                            FeatureKey = "AI_MATCHING",
                            FeatureName = "AI Matching",
                            IsActive = true,
                            PlanId = 2,
                            Type = 1,
                            Value = "true"
                        },
                        new
                        {
                            Id = 9,
                            FeatureKey = "BOOST_PROFILE",
                            FeatureName = "Profile Boost",
                            IsActive = true,
                            PlanId = 2,
                            Type = 1,
                            Value = "true"
                        },
                        new
                        {
                            Id = 10,
                            FeatureKey = "COMPLIMENT_ACCESS",
                            FeatureName = "Compliment Access",
                            IsActive = true,
                            PlanId = 2,
                            Type = 1,
                            Value = "false"
                        },
                        new
                        {
                            Id = 11,
                            FeatureKey = "MAX_APPLY",
                            FeatureName = "Max Applications",
                            IsActive = true,
                            PlanId = 3,
                            Type = 2,
                            Value = "-1"
                        },
                        new
                        {
                            Id = 12,
                            FeatureKey = "MAX_PORTFOLIOS",
                            FeatureName = "Max Portfolios",
                            IsActive = true,
                            PlanId = 3,
                            Type = 2,
                            Value = "-1"
                        },
                        new
                        {
                            Id = 13,
                            FeatureKey = "AI_MATCHING",
                            FeatureName = "AI Matching",
                            IsActive = true,
                            PlanId = 3,
                            Type = 1,
                            Value = "true"
                        },
                        new
                        {
                            Id = 14,
                            FeatureKey = "BOOST_PROFILE",
                            FeatureName = "Profile Boost",
                            IsActive = true,
                            PlanId = 3,
                            Type = 1,
                            Value = "true"
                        },
                        new
                        {
                            Id = 15,
                            FeatureKey = "COMPLIMENT_ACCESS",
                            FeatureName = "Compliment Access",
                            IsActive = true,
                            PlanId = 3,
                            Type = 1,
                            Value = "true"
                        });
                });

            modelBuilder.Entity("Subscription.Domain.Entities.ProcessedEvent", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ProcessedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("EventId");

                    b.HasIndex("ProcessedAt");

                    b.ToTable("ProcessedEvents", (string)null);
                });

            modelBuilder.Entity("Subscription.Domain.Entities.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoRenew")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Status");

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("Subscription.Domain.Entities.PlanFeature", b =>
                {
                    b.HasOne("Subscription.Domain.Entities.Plan", "Plan")
                        .WithMany("Features")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Subscription.Domain.Entities.UserSubscription", b =>
                {
                    b.HasOne("Subscription.Domain.Entities.Plan", "Plan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Subscription.Domain.Entities.Plan", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
