<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Moq" Version="4.18.4" />
    <PackageReference Include="xunit" Version="2.5.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Shared\RecruitmentPlatform.AI\RecruitmentPlatform.AI.csproj" />
    <ProjectReference Include="..\..\Services\Community\Community.Application\Community.Application.csproj" />
    <ProjectReference Include="..\..\Services\Company\Company.Application\Company.Application.csproj" />
  </ItemGroup>
</Project>
