// <auto-generated />
using System;
using Company.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Company.Infrastructure.Migrations
{
    [DbContext(typeof(CompanyDbContext))]
    [Migration("20260501000001_AddPostModerationFields")]
    partial class AddPostModerationFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("companysvc")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Company.Domain.Entities.CompanyPost", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("postId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("address");

                    b.Property<string>("Benefits")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("benefits");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("companyId");

                    b.Property<string>("CoverImageVideo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("coverImageVideo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createAt");

                    b.Property<string>("EmploymentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("employmentType");

                    b.Property<int?>("ExperienceYear")
                        .HasColumnType("int")
                        .HasColumnName("experienceYear");

                    b.Property<string>("JobDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("jobDescription");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("position");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("RequirementsMandatory")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("requirementsMandatory");

                    b.Property<string>("RequirementsPreferred")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("requirementsPreferred");

                    b.Property<string>("ReviewReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("reviewReason");

                    b.Property<int?>("ReviewStatus")
                        .HasColumnType("int")
                        .HasColumnName("reviewStatus");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("reviewedAt");

                    b.Property<string>("Salary")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("salary");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.HasKey("PostId");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("IX_Post_CompanyId");

                    b.HasIndex("Status", "CreatedAt", "PostId")
                        .HasDatabaseName("IX_Post_Status_CreateAt_PostId");

                    b.ToTable("COMPANY_POST", "companysvc");
                });

#pragma warning restore 612, 618
        }
    }
}
