// <auto-generated />
using System;
using Company.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Company.Infrastructure.Migrations
{
    [DbContext(typeof(CompanyDbContext))]
    [Migration("20260515061328_AddCompanyPostReport")]
    partial class AddCompanyPostReport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("companysvc")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Company.Domain.Entities.CompanyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("avatarUrl");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("COMPANY", "companysvc");
                });

            modelBuilder.Entity("Company.Domain.Entities.CompanyPost", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("postId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("address");

                    b.Property<string>("Benefits")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("benefits");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int")
                        .HasColumnName("companyId");

                    b.Property<string>("CoverImageVideo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("coverImageVideo");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createAt");

                    b.Property<string>("Embedding")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("embedding");

                    b.Property<string>("EmbeddingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("embeddingStatus");

                    b.Property<DateTime?>("EmbeddingUpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("embeddingUpdatedAt");

                    b.Property<int>("EmbeddingVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("embeddingVersion");

                    b.Property<string>("EmploymentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("employmentType");

                    b.Property<int?>("ExperienceYear")
                        .HasColumnType("int")
                        .HasColumnName("experienceYear");

                    b.Property<string>("JobDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("jobDescription");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("position");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<string>("RequirementsMandatory")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("requirementsMandatory");

                    b.Property<string>("RequirementsPreferred")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("requirementsPreferred");

                    b.Property<string>("ReviewReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("reviewReason");

                    b.Property<int?>("ReviewStatus")
                        .HasColumnType("int")
                        .HasColumnName("reviewStatus");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("reviewedAt");

                    b.Property<string>("Salary")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("salary");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("status");

                    b.HasKey("PostId");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("IX_Post_CompanyId");

                    b.HasIndex("Status", "CreatedAt", "PostId")
                        .HasDatabaseName("IX_Post_Status_CreateAt_PostId");

                    b.ToTable("COMPANY_POST", "companysvc");
                });

            modelBuilder.Entity("Company.Domain.Entities.CompanyPostMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("address");

                    b.Property<int>("CompanyPostId")
                        .HasColumnType("int")
                        .HasColumnName("companyPostId");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CompanyPostId")
                        .HasDatabaseName("IX_PostMedia_PostId");

                    b.ToTable("COMPANY_POST_MEDIA", "companysvc");
                });

            modelBuilder.Entity("Company.Domain.Entities.CompanyPostReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyPostId")
                        .HasColumnType("int")
                        .HasColumnName("companyPostId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("reason");

                    b.Property<int>("ReporterUserId")
                        .HasColumnType("int")
                        .HasColumnName("reporterUserId");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("reviewNote");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("reviewedAt");

                    b.Property<int?>("ReviewedByUserId")
                        .HasColumnType("int")
                        .HasColumnName("reviewedByUserId");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id");

                    b.HasIndex("CompanyPostId")
                        .HasDatabaseName("IX_PostReport_PostId");

                    b.HasIndex("CompanyPostId", "ReporterUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_PostReport_Post_Reporter");

                    b.ToTable("COMPANY_POST_REPORT", "companysvc");
                });

            modelBuilder.Entity("Company.Domain.Entities.CompanyPostSave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyPostId")
                        .HasColumnType("int")
                        .HasColumnName("companyPostId");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.HasIndex("CompanyPostId");

                    b.HasIndex("UserId", "CompanyPostId")
                        .IsUnique()
                        .HasDatabaseName("IX_PostSave_User_Post");

                    b.ToTable("COMPANY_POST_SAVE", "companysvc");
                });

            modelBuilder.Entity("Company.Domain.Entities.CompanyPostMedia", b =>
                {
                    b.HasOne("Company.Domain.Entities.CompanyPost", "CompanyPost")
                        .WithMany("Media")
                        .HasForeignKey("CompanyPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PostMedia_Post");

                    b.Navigation("CompanyPost");
                });

            modelBuilder.Entity("Company.Domain.Entities.CompanyPostReport", b =>
                {
                    b.HasOne("Company.Domain.Entities.CompanyPost", "CompanyPost")
                        .WithMany()
                        .HasForeignKey("CompanyPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PostReport_Post");

                    b.Navigation("CompanyPost");
                });

            modelBuilder.Entity("Company.Domain.Entities.CompanyPostSave", b =>
                {
                    b.HasOne("Company.Domain.Entities.CompanyPost", "CompanyPost")
                        .WithMany("Saves")
                        .HasForeignKey("CompanyPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PostSave_Post");

                    b.Navigation("CompanyPost");
                });

            modelBuilder.Entity("Company.Domain.Entities.CompanyPost", b =>
                {
                    b.Navigation("Media");

                    b.Navigation("Saves");
                });
#pragma warning restore 612, 618
        }
    }
}
